clone_folder: c:\projects\cmake-init
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
- Win32

matrix:
  fast_finish: true

init:
- if "%platform%"=="x64" (set generator="Visual Studio 15 2017 Win64")
- if "%platform%"=="x64" (set arch=x64)
- if "%platform%"=="Win32" (set generator="Visual Studio 15 2017")
- if "%platform%"=="Win32" (set arch=x86)
- echo %platform%
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- echo %generator%

cache: c:\tools\vcpkg\installed

before_build:
- cmd: |-
    vcpkg install stb:%arch%-windows glm:%arch%-windows glew:%arch%-windows glfw3:%arch%-windows spdlog:%arch%-windows boost-test:%arch%-windows
    mkdir build
    cd build
    cmake --version
    cmake .. -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G %generator%

build:
  project: c:\projects\cmake-init\build\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
  parallel: true

test_script:
- cd c:\projects\cmake-init\build\
- ctest -C %configuration%