clone_folder: c:\projects\cmake-init
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
  - arch: Win32

matrix:
  fast_finish: true

init:
- set arch=
- if "%arch%"=="Win64" (set arch= Win64)
- if "%arch%"=="Win32" (set arch=)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (set generator="Visual Studio 15 2017%arch%")
- echo %generator%

cache: c:\tools\vcpkg\installed

before_build:
- cmd: |-
    vcpkg install stb:x64-windows glm:x64-windows glew:x64-windows glfw3:x64-windows spdlog:x64-windows boost-test:x64-windows
    mkdir build
    cd build
    cmake --version
    cmake .. -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake -G %generator%

build:
  project: c:\projects\cmake-init\build\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
  parallel: true

test_script:
- cd c:\projects\cmake-init\build\
- ctest -C %configuration%